---
name: Molecule CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        test_distro:
          - centos:6
          - centos:7
          - centos:8
          - amazonlinux:1
          - amazonlinux:2
          - debian:8
          - debian:9
          - debian:10
          - ubuntu:16.04
          - ubuntu:18.04
          - ubuntu:20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r molecule/requirements.txt
      - name: Test with molecule
        run: molecule test --all
        env:
          TEST_DISTRO: ${{ matrix.molecule_distro }}
